apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prophious-project-secret
spec:
  provider: aws
  secretObjects:
  - secretName: Prophious-Project-secret
    type: Opaque
    data:
    - objectName: username
      key: username
    - objectName: password
      key: password
  parameters:
    objects: |
        - objectName: "Prophious-Project-secret"
          objectType: "secretsmanager"
          jmesPath:
            - path: "username"
              objectAlias: "username"
            - path: "password"
              objectAlias: "password"